name: Check PR Labels

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Check PR labels
      id: check_labels
      run: |
        required_labels=("bug" "enhancement")
        labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

        missing_labels=()
        for label in "${required_labels[@]}"; do
          if ! echo "$labels" | grep -q "$label"; then
            missing_labels+=("$label")
          fi
        done

        if [ ${#missing_labels[@]} -ne 0 ]; then
          echo "Missing required labels: ${missing_labels[@]}"
          echo "::set-output name=labels_missing::true"
        else
          echo "::set-output name=labels_missing::false"
        fi

    - name: Fail if labels are missing
      if: steps.check_labels.outputs.labels_missing == 'true'
      run: |
        echo "PR is missing required labels."
        exit 1
